### ISSUE TITLE
Is there any option to provide string output instead of stream?

### ISSUE THREAD

**Issue by namnm** [nfroidure/svgicons2svgfont#46]
I use this as a step for generating woff and woff2 icon font at the end.
Currently I must use data event to concat chunk, and end event to start next step.
Is there any option to get output as string (or buffer) directly?

**Comment by nfroidure** [comment]
There are a lot of modules that can do this for your (like stream-buffers), i think we don't need to add this to the module since it is really easy to do what you want.

On the other hand, i'm planning to convert all my stream based libraries to pure functional ones and let users decide if they want to use streams or work on a buffer. I'm not close to ship that version though, using a module to buffer the stream is the best solution for now.
