### ISSUE TITLE
Why preferGlobal?

### ISSUE THREAD

**Issue by jcrben** [nfroidure/svgicons2svgfont#68]
At https://github.com/nfroidure/svgicons2svgfont/blob/f2a6a6e332952bb0bd278df2df8542d2b6f919d0/package.json#L55

Does this project envision people mostly using this as a CLI app rather than an embedded dependency in their apps?

Noticed this when installing the dependencies for https://github.com/webpack/webpack.js.org.

I tend to think of global dependencies as an antipattern, so I'm curious about the reasoning. Also not sure it helps to warn since it seems that people are going to install this as a dependency.

**Comment by nfroidure** [comment]
This module is aging. At the beginning of the NodeJS adoption, there was a lil confusion on the real `preferGlobal` meaning. I thought it was meant to underline there was a CLI interface.

But, now, indeed, I think that installing this module globally make no sense since the npm scripts has grown in usage. Feel free to PR the project to fix it.
